repos:
  # basic pre-commit hooks
  - repo: 'https://github.com/pre-commit/pre-commit-hooks'
    rev: v2.4.0
    hooks:
      - id: trailing-whitespace
      - id: check-merge-conflict
      - id: check-json

  # import sorting with isort
  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.10.1
    hooks:
      - id: isort
        args: ['--profile', 'black']

  # detecting and removing unused imports with unimport
  - repo: https://github.com/hakancelik96/unimport
    rev: 0.11.1
    hooks:
      - id: unimport
        args: [-r, --include-star-import, --ignore-init]
        files: "\\.(py)$"

  # enforcing the use of new python syntax with pyupgrade
  - repo: https://github.com/asottile/pyupgrade
    rev: v2.7.2
    hooks:
      - id: pyupgrade

  # code formatting with black
  - repo: 'https://github.com/psf/black'
    rev: 22.6.0
    hooks:
      - id: black
        language_version: python3

  # linting and code analysis with flake8
  - repo: https://github.com/pycqa/flake8
    rev: 3.8.3
    hooks:
      - id: flake8
        args: [--max-line-length=160, --ignore=E203 E231 E800 W503 ANN101 ANN102 ANN204 N806 N803 N802 N817 ANN401]
        additional_dependencies: [flake8-bugbear, flake8-comprehensions, flake8-eradicate, pep8-naming, flake8-annotations]
